package router

import (
	"ops-admin/backend/config"
	"ops-admin/backend/controller"
	"ops-admin/backend/middleware"
	"ops-admin/backend/service"
	"os"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

func New(cfg *config.Config, db *gorm.DB) (*gin.Engine, *service.Service) {
	if cfg.App.Mode == gin.ReleaseMode {
		gin.SetMode(gin.ReleaseMode)
	}

	engine := gin.New()
	engine.Use(gin.Logger(), gin.Recovery(), middleware.CORS())
	_ = os.MkdirAll("uploads", 0o755)
	engine.Static("/uploads", "./uploads")

	svc := service.New(db)
	svc.ConfigureCertificate(service.CertificateRuntimeConfig{
		Email:                 cfg.SSL.ACMEEmail,
		ProductionCA:          cfg.SSL.ProductionCA,
		StagingCA:             cfg.SSL.StagingCA,
		DNSPollingSeconds:     cfg.SSL.DNSPollingSeconds,
		DNSPropagationSeconds: cfg.SSL.DNSPropagationSeconds,
		ExpiryWarningDays:     cfg.SSL.ExpiryWarningDays,
	})
	ctl := controller.New(svc)

	engine.GET("/ping", ctl.Ping)

	api := engine.Group("/api/v1")
	{
		api.POST("/login", ctl.Login)
		api.POST("/auth/refresh", ctl.RefreshToken)
		api.POST("/auth/logout", ctl.Logout)
		api.GET("/systemConfig/public", ctl.GetSystemConfig)
		api.GET("/integration/public/:token", ctl.GetPublicIntegrationNavigation)
		api.GET("/asset/terminal/ws", ctl.AssetTerminalWS)
		api.GET("/k8s/pod/terminal/ws", ctl.K8sPodTerminalWS)
	}

	authGroup := api.Group("")
	authGroup.Use(middleware.Auth(db), middleware.OperationLog(db))
	{
		authGroup.GET("/profile", ctl.Profile)
		authGroup.GET("/domain/public/accounts", middleware.RequirePermission(db, "domains:account:list"), ctl.ListPublicDNSAccounts)
		authGroup.GET("/domain/public/accounts/options", middleware.RequireAnyPermission(db, "domains:account:list", "domains:public:list", "domains:ssl:view"), ctl.PublicDNSAccountOptions)
		authGroup.GET("/domain/public/accounts/detail", middleware.RequirePermission(db, "domains:account:list"), ctl.GetPublicDNSAccount)
		authGroup.POST("/domain/public/accounts/save", middleware.RequireCreateOrEditPermission(db, "domains:account:add", "domains:account:edit"), ctl.SavePublicDNSAccount)
		authGroup.DELETE("/domain/public/accounts/delete", middleware.RequirePermission(db, "domains:account:delete"), ctl.DeletePublicDNSAccount)
		authGroup.POST("/domain/public/accounts/test", middleware.RequirePermission(db, "domains:account:test"), ctl.TestPublicDNSAccount)
		authGroup.GET("/domain/public/domains", middleware.RequirePermission(db, "domains:public:list"), ctl.ListPublicDomains)
		authGroup.POST("/domain/public/domains/sync", middleware.RequirePermission(db, "domains:public:sync"), ctl.SyncPublicDomains)
		authGroup.GET("/domain/public/records", middleware.RequireAnyPermission(db, "domains:public:list", "domains:public:record"), ctl.ListPublicDNSRecords)
		authGroup.POST("/domain/public/records/mutate", middleware.RequirePermission(db, "domains:public:record"), ctl.MutatePublicDNSRecord)
		authGroup.POST("/domain/public/records/batch", middleware.RequirePermission(db, "domains:public:batch"), ctl.BatchPublicDNSRecords)
		authGroup.GET("/domain/internal/settings", middleware.RequireAnyPermission(db, "domains:settings:view", "domains:internal:list", "domains:query:test"), ctl.GetInternalDNSSettings)
		authGroup.PUT("/domain/internal/settings", middleware.RequirePermission(db, "domains:settings:save"), ctl.SaveInternalDNSSettings)
		authGroup.GET("/domain/internal/zones", middleware.RequirePermission(db, "domains:internal:list"), ctl.ListInternalDNSZones)
		authGroup.POST("/domain/internal/zones/save", middleware.RequireCreateOrEditPermission(db, "domains:internal:zone:add", "domains:internal:zone:edit"), ctl.SaveInternalDNSZone)
		authGroup.DELETE("/domain/internal/zones/delete", middleware.RequirePermission(db, "domains:internal:zone:delete"), ctl.DeleteInternalDNSZone)
		authGroup.GET("/domain/internal/records", middleware.RequireAnyPermission(db, "domains:internal:list", "domains:internal:record"), ctl.ListInternalDNSRecords)
		authGroup.POST("/domain/internal/records/save", middleware.RequirePermission(db, "domains:internal:record"), ctl.SaveInternalDNSRecord)
		authGroup.DELETE("/domain/internal/records/delete", middleware.RequirePermission(db, "domains:internal:record"), ctl.DeleteInternalDNSRecord)
		authGroup.POST("/domain/internal/records/batch", middleware.RequirePermission(db, "domains:internal:record"), ctl.BatchInternalDNSRecords)
		authGroup.POST("/domain/internal/query", middleware.RequirePermission(db, "domains:query:test"), ctl.TestDNSResolution)
		authGroup.GET("/domain/audit", middleware.RequirePermission(db, "domains:audit:list"), ctl.ListDNSAuditLogs)
		authGroup.GET("/domain/public/certificates", middleware.RequirePermission(db, "domains:ssl:view"), ctl.ListSSLCertificates)
		authGroup.GET("/domain/public/certificates/detail", middleware.RequirePermission(db, "domains:ssl:view"), ctl.GetSSLCertificate)
		authGroup.GET("/domain/public/certificates/domain-options", middleware.RequirePermission(db, "domains:ssl:view"), ctl.SSLCertificateDomainOptions)
		authGroup.GET("/domain/public/certificates/tasks", middleware.RequirePermission(db, "domains:ssl:view"), ctl.ListSSLCertificateTasks)
		authGroup.GET("/domain/public/certificates/audits", middleware.RequirePermission(db, "domains:ssl:view"), ctl.ListSSLCertificateAudits)
		authGroup.POST("/domain/public/certificates/sync", middleware.RequirePermission(db, "domains:ssl:sync"), ctl.SyncSSLCertificates)
		authGroup.POST("/domain/public/certificates/upload", middleware.RequirePermission(db, "domains:ssl:upload"), ctl.UploadSSLCertificate)
		authGroup.POST("/domain/public/certificates/apply", middleware.RequirePermission(db, "domains:ssl:apply"), ctl.ApplySSLCertificate)
		authGroup.POST("/domain/public/certificates/renew", middleware.RequirePermission(db, "domains:ssl:renew"), ctl.RenewSSLCertificate)
		authGroup.POST("/domain/public/certificates/resync", middleware.RequirePermission(db, "domains:ssl:sync"), ctl.ResyncSSLCertificate)
		authGroup.PUT("/domain/public/certificates/renew-settings", middleware.RequirePermission(db, "domains:ssl:settings"), ctl.UpdateSSLCertificateRenewSettings)
		authGroup.DELETE("/domain/public/certificates/delete", middleware.RequirePermission(db, "domains:ssl:delete"), ctl.DeleteSSLCertificate)
		authGroup.GET("/domain/public/certificates/download", middleware.RequirePermission(db, "domains:ssl:download"), ctl.DownloadSSLCertificate)
		authGroup.GET("/domain/public/certificates/download-private", middleware.RequirePermission(db, "domains:ssl:download-key"), ctl.DownloadSSLCertificatePrivate)
		authGroup.GET("/systemConfig", ctl.GetSystemConfig)
		authGroup.PUT("/systemConfig", ctl.UpdateSystemConfig)
		authGroup.POST("/systemConfig/upload", ctl.UploadSystemAsset)
		authGroup.GET("/system/ldap/config", ctl.GetLDAPConfig)
		authGroup.PUT("/system/ldap/config", ctl.SaveLDAPConfig)
		authGroup.POST("/system/ldap/test", ctl.TestLDAPConfig)
		authGroup.GET("/integration/navigation/group/list", ctl.GetIntegrationNavigationGroupList)
		authGroup.POST("/integration/navigation/group/save", ctl.SaveIntegrationNavigationGroup)
		authGroup.DELETE("/integration/navigation/group/delete", ctl.DeleteIntegrationNavigationGroup)
		authGroup.POST("/integration/navigation/group/token", ctl.RegenerateIntegrationPublicToken)
		authGroup.GET("/integration/navigation/list", ctl.GetIntegrationNavigationList)
		authGroup.POST("/integration/navigation/save", ctl.SaveIntegrationNavigation)
		authGroup.DELETE("/integration/navigation/delete", ctl.DeleteIntegrationNavigation)
		authGroup.GET("/integration/ai/model/list", ctl.GetIntegrationAIModelList)
		authGroup.POST("/integration/ai/model/save", ctl.SaveIntegrationAIModel)
		authGroup.DELETE("/integration/ai/model/delete", ctl.DeleteIntegrationAIModel)
		authGroup.POST("/integration/ai/model/test", ctl.TestIntegrationAIModel)
		authGroup.GET("/integration/ai/conversation/list", ctl.GetIntegrationAIConversationList)
		authGroup.GET("/integration/ai/conversation/detail", ctl.GetIntegrationAIConversationDetail)
		authGroup.POST("/integration/ai/conversation/save", ctl.SaveIntegrationAIConversation)
		authGroup.DELETE("/integration/ai/conversation/delete", ctl.DeleteIntegrationAIConversation)
		authGroup.POST("/integration/ai/chat/send", ctl.SendIntegrationAIChat)
		authGroup.GET("/integration/ai/knowledge-base/list", ctl.GetIntegrationAIKnowledgeDocumentList)
		authGroup.POST("/integration/ai/knowledge-base/save", ctl.SaveIntegrationAIKnowledgeDocument)
		authGroup.POST("/integration/ai/knowledge-base/upload", ctl.UploadIntegrationAIKnowledgeDocument)
		authGroup.DELETE("/integration/ai/knowledge-base/delete", ctl.DeleteIntegrationAIKnowledgeDocument)
		authGroup.GET("/integration/ai/tool/list", ctl.GetIntegrationAIToolList)
		authGroup.PUT("/integration/ai/tool/update", ctl.UpdateIntegrationAITool)
		authGroup.POST("/integration/ai/tool/execute", ctl.ExecuteIntegrationAITool)
		authGroup.POST("/integration/ai/action/confirm", ctl.ConfirmIntegrationAIAction)
		authGroup.POST("/integration/ai/action/reject", ctl.RejectIntegrationAIAction)
		authGroup.GET("/integration/finops/account/list", ctl.GetFinOpsAccountList)
		authGroup.POST("/integration/finops/account/save", ctl.SaveFinOpsAccount)
		authGroup.DELETE("/integration/finops/account/delete", ctl.DeleteFinOpsAccount)
		authGroup.POST("/integration/finops/account/test", ctl.TestFinOpsAccount)
		authGroup.GET("/integration/finops/dashboard", ctl.GetFinOpsDashboard)
		authGroup.GET("/integration/finops/breakdown", ctl.GetFinOpsBreakdown)
		authGroup.GET("/integration/finops/breakdown/latest-month", ctl.GetFinOpsLatestBreakdownMonth)
		authGroup.GET("/integration/finops/resource/list", ctl.GetFinOpsResources)
		authGroup.GET("/integration/finops/recommendation/list", ctl.GetFinOpsRecommendationList)
		authGroup.POST("/integration/finops/recommendation/generate", ctl.GenerateFinOpsRecommendations)
		authGroup.PUT("/integration/finops/recommendation/status", ctl.UpdateFinOpsRecommendation)
		authGroup.DELETE("/integration/finops/recommendation/delete", ctl.DeleteFinOpsRecommendation)
		authGroup.GET("/integration/finops/sync/logs", ctl.GetFinOpsSyncLogs)
		authGroup.POST("/integration/finops/sync/trigger", ctl.TriggerFinOpsSync)
		authGroup.POST("/integration/finops/cost/import", ctl.ImportFinOpsCosts)
		authGroup.GET("/admin/ldap/users", ctl.PreviewLDAPUsers)
		authGroup.POST("/admin/ldap/sync", ctl.SyncLDAPUsers)

		authGroup.GET("/admin/list", ctl.GetSysAdminList)
		authGroup.GET("/admin/info", ctl.GetSysAdminInfo)
		authGroup.POST("/admin/add", ctl.CreateSysAdmin)
		authGroup.PUT("/admin/update", ctl.UpdateSysAdmin)
		authGroup.DELETE("/admin/delete", ctl.DeleteSysAdmin)
		authGroup.PUT("/admin/updateStatus", ctl.UpdateSysAdminStatus)
		authGroup.PUT("/admin/updatePassword", ctl.ResetSysAdminPassword)
		authGroup.PUT("/admin/updatePersonal", ctl.UpdatePersonal)
		authGroup.PUT("/admin/updatePersonalPassword", ctl.UpdatePersonalPassword)

		authGroup.GET("/role/list", ctl.GetRoleList)
		authGroup.GET("/role/vo/list", ctl.QuerySysRoleVoList)
		authGroup.GET("/role/info", ctl.GetRoleInfo)
		authGroup.POST("/role/add", ctl.CreateRole)
		authGroup.PUT("/role/update", ctl.UpdateRole)
		authGroup.DELETE("/role/delete", ctl.DeleteRole)
		authGroup.PUT("/role/updateStatus", ctl.UpdateRoleStatus)
		authGroup.GET("/role/vo/idList", ctl.QueryRoleMenuIDList)
		authGroup.PUT("/role/assignPermissions", ctl.AssignPermissions)

		authGroup.GET("/menu/list", ctl.GetMenuList)
		authGroup.GET("/menu/vo/list", ctl.QuerySysMenuVoList)
		authGroup.GET("/menu/info", ctl.GetMenuInfo)
		authGroup.POST("/menu/add", ctl.CreateMenu)
		authGroup.PUT("/menu/update", ctl.UpdateMenu)
		authGroup.DELETE("/menu/delete", ctl.DeleteMenu)

		authGroup.GET("/dept/list", ctl.GetDeptList)
		authGroup.GET("/dept/vo/list", ctl.QuerySysDeptVoList)
		authGroup.GET("/dept/info", ctl.GetDeptInfo)
		authGroup.GET("/dept/users", ctl.GetDeptUsers)
		authGroup.POST("/dept/add", ctl.CreateDept)
		authGroup.PUT("/dept/update", ctl.UpdateDept)
		authGroup.DELETE("/dept/delete", ctl.DeleteDept)

		authGroup.GET("/post/list", ctl.GetPostList)
		authGroup.GET("/post/vo/list", ctl.QuerySysPostVoList)
		authGroup.GET("/post/info", ctl.GetPostInfo)
		authGroup.POST("/post/add", ctl.CreatePost)
		authGroup.PUT("/post/update", ctl.UpdatePost)
		authGroup.PUT("/post/updateStatus", ctl.UpdatePostStatus)
		authGroup.DELETE("/post/delete", ctl.DeletePost)
		authGroup.DELETE("/post/batch/delete", ctl.BatchDeletePost)

		authGroup.GET("/sysLoginInfo/list", ctl.GetLoginLogList)
		authGroup.DELETE("/sysLoginInfo/delete", ctl.DeleteLoginLog)
		authGroup.DELETE("/sysLoginInfo/batch/delete", ctl.BatchDeleteLoginLog)
		authGroup.DELETE("/sysLoginInfo/clean", ctl.CleanLoginLog)

		authGroup.GET("/sysOperationLog/list", ctl.GetOperationLogList)
		authGroup.DELETE("/sysOperationLog/delete", ctl.DeleteOperationLog)
		authGroup.DELETE("/sysOperationLog/batch/delete", ctl.BatchDeleteOperationLog)
		authGroup.DELETE("/sysOperationLog/clean", ctl.CleanOperationLog)

		authGroup.GET("/asset/host/list", ctl.GetAssetHostList)
		authGroup.GET("/asset/service/list", ctl.GetAssetServiceList)
		authGroup.GET("/asset/service/info", ctl.GetAssetServiceInfo)
		authGroup.POST("/asset/service/save", ctl.SaveAssetService)
		authGroup.DELETE("/asset/service/delete", ctl.DeleteAssetService)
		authGroup.GET("/asset/service/k8s/catalog", ctl.GetAssetServiceK8sCatalog)
		authGroup.GET("/asset/service/runtime-topology", ctl.GetAssetServiceRuntimeTopology)
		authGroup.GET("/asset/service/workload/runtime", ctl.GetAssetServiceWorkloadRuntime)
		authGroup.GET("/asset/service/workload/topology", ctl.GetAssetServiceWorkloadTopology)
		authGroup.GET("/asset/service/workload/metrics", ctl.GetAssetServiceWorkloadMetrics)
		authGroup.GET("/asset/service/workload/rollout-history", ctl.GetAssetServiceWorkloadRolloutHistory)
		authGroup.POST("/asset/service/workload/rollback", ctl.RollbackAssetServiceWorkload)
		authGroup.GET("/asset/service/workload/logs", ctl.GetAssetServiceWorkloadLogs)
		authGroup.GET("/asset/service/diagnosis/processes", ctl.GetAssetServiceDiagnosisProcesses)
		authGroup.GET("/asset/service/diagnosis/environment", ctl.GetAssetServiceDiagnosisEnvironment)
		authGroup.GET("/asset/service/diagnosis/run", ctl.RunAssetServiceDiagnosis)
		authGroup.POST("/asset/service/diagnosis/arthas/download", ctl.DownloadAssetServiceArthas)
		authGroup.POST("/asset/service/diagnosis/arthas/upload", ctl.UploadAssetServiceArthas)
		authGroup.GET("/asset/overview", ctl.GetAssetOverview)
		authGroup.GET("/asset/change-log/list", ctl.GetAssetChangeLogs)
		authGroup.GET("/asset/host/info", ctl.GetAssetHostInfo)
		authGroup.GET("/asset/host/metrics", ctl.GetAssetHostMetrics)
		authGroup.GET("/asset/host/template", ctl.DownloadAssetHostTemplate)
		authGroup.POST("/asset/host/add", ctl.CreateAssetHost)
		authGroup.POST("/asset/host/import", ctl.ImportAssetHosts)
		authGroup.POST("/asset/host/cloudSync", ctl.SyncAssetHostsFromCloud)
		authGroup.PUT("/asset/host/update", ctl.UpdateAssetHost)
		authGroup.POST("/asset/host/sync", ctl.SyncAssetHost)
		authGroup.POST("/asset/host/batch/sync", ctl.BatchSyncAssetHosts)
		authGroup.PUT("/asset/host/batch/credential", ctl.BatchReplaceAssetHostCredential)
		authGroup.DELETE("/asset/host/group/remove", ctl.RemoveAssetHostsFromGroup)
		authGroup.DELETE("/asset/host/delete", ctl.DeleteAssetHost)
		authGroup.DELETE("/asset/host/batch/delete", ctl.BatchDeleteAssetHosts)

		authGroup.GET("/asset/hostGroup/list", ctl.GetAssetHostGroupList)
		authGroup.GET("/asset/hostGroup/info", ctl.GetAssetHostGroupInfo)
		authGroup.POST("/asset/hostGroup/add", ctl.CreateAssetHostGroup)
		authGroup.PUT("/asset/hostGroup/update", ctl.UpdateAssetHostGroup)
		authGroup.DELETE("/asset/hostGroup/delete", ctl.DeleteAssetHostGroup)

		authGroup.GET("/asset/credential/list", ctl.GetAssetCredentialList)
		authGroup.GET("/asset/credential/options", ctl.GetAssetCredentialOptions)
		authGroup.GET("/asset/credential/info", ctl.GetAssetCredentialInfo)
		authGroup.POST("/asset/credential/add", ctl.CreateAssetCredential)
		authGroup.PUT("/asset/credential/update", ctl.UpdateAssetCredential)
		authGroup.DELETE("/asset/credential/delete", ctl.DeleteAssetCredential)

		authGroup.GET("/asset/cloudAccount/list", ctl.GetAssetCloudAccountList)
		authGroup.GET("/asset/cloudAccount/options", ctl.GetAssetCloudAccountOptions)
		authGroup.GET("/asset/cloudAccount/info", ctl.GetAssetCloudAccountInfo)
		authGroup.POST("/asset/cloudAccount/add", ctl.CreateAssetCloudAccount)
		authGroup.PUT("/asset/cloudAccount/update", ctl.UpdateAssetCloudAccount)
		authGroup.DELETE("/asset/cloudAccount/delete", ctl.DeleteAssetCloudAccount)
		authGroup.GET("/asset/gateway/list", ctl.GetAssetGatewayList)
		authGroup.GET("/asset/gateway/options", ctl.GetAssetGatewayOptions)
		authGroup.GET("/asset/gateway/info", ctl.GetAssetGatewayInfo)
		authGroup.POST("/asset/gateway/add", ctl.CreateAssetGateway)
		authGroup.PUT("/asset/gateway/update", ctl.UpdateAssetGateway)
		authGroup.DELETE("/asset/gateway/delete", ctl.DeleteAssetGateway)
		authGroup.PUT("/asset/gateway/status", ctl.UpdateAssetGatewayStatus)
		authGroup.POST("/asset/gateway/test", ctl.TestAssetGatewayConnection)

		authGroup.GET("/asset/database/list", ctl.GetAssetDatabaseList)
		authGroup.GET("/asset/database/info", ctl.GetAssetDatabaseInfo)
		authGroup.GET("/asset/database/metrics", ctl.GetAssetDatabaseMetrics)
		authGroup.POST("/asset/database/add", ctl.CreateAssetDatabase)
		authGroup.PUT("/asset/database/update", ctl.UpdateAssetDatabase)
		authGroup.DELETE("/asset/database/delete", ctl.DeleteAssetDatabase)
		authGroup.POST("/asset/database/test", ctl.TestAssetDatabaseConnection)

		authGroup.GET("/dbms/workbench", ctl.GetDatabaseWorkbench)
		authGroup.GET("/dbms/schema/tree", ctl.GetDatabaseSchemaTree)
		authGroup.POST("/dbms/schema/create", ctl.CreateDatabaseSchema)
		authGroup.GET("/dbms/charset/options", ctl.GetDatabaseCharsetOptions)
		authGroup.GET("/dbms/table/data", ctl.GetDatabaseTableData)
		authGroup.GET("/dbms/resource/data", ctl.GetDatabaseResourceData)
		authGroup.POST("/dbms/sql/execute", ctl.ExecuteDatabaseSQL)
		authGroup.POST("/dbms/sql/analyze", ctl.AnalyzeDatabaseSQL)
		authGroup.POST("/dbms/redis/analyze", ctl.AnalyzeRedisCommand)
		authGroup.POST("/dbms/redis/execute", ctl.ExecuteRedisCommand)
		authGroup.GET("/dbms/sql/history", ctl.GetDatabaseSQLHistory)
		authGroup.POST("/dbms/table/row/insert", ctl.InsertDatabaseTableRow)
		authGroup.PUT("/dbms/table/row/update", ctl.UpdateDatabaseTableRow)
		authGroup.DELETE("/dbms/table/row/delete", ctl.DeleteDatabaseTableRow)
		authGroup.POST("/dbms/task/export", ctl.CreateExportTask)
		authGroup.POST("/dbms/task/import", ctl.CreateImportTask)
		authGroup.POST("/dbms/task/import/precheck", ctl.PrecheckImportTask)
		authGroup.POST("/dbms/task/batch-sql", ctl.CreateBatchSQLTask)
		authGroup.GET("/dbms/task/list", ctl.GetTransferTaskList)
		authGroup.GET("/dbms/task/download", ctl.DownloadTransferTask)
		authGroup.GET("/dbms/backup/plan/list", ctl.GetDatabaseBackupPlanList)
		authGroup.POST("/dbms/backup/plan/save", ctl.SaveDatabaseBackupPlan)
		authGroup.DELETE("/dbms/backup/plan/delete", ctl.DeleteDatabaseBackupPlan)
		authGroup.POST("/dbms/backup/plan/run", ctl.RunDatabaseBackupPlan)
		authGroup.POST("/dbms/backup/manual", ctl.RunManualDatabaseBackup)
		authGroup.GET("/dbms/backup/record/list", ctl.GetDatabaseBackupRecordList)
		authGroup.GET("/dbms/backup/download", ctl.DownloadDatabaseBackup)
		authGroup.POST("/dbms/backup/import", ctl.CreateDatabaseBackupImportTask)

		authGroup.GET("/ops/script/list", ctl.GetOpsScriptList)
		authGroup.GET("/ops/script/options", ctl.GetOpsScriptOptions)
		authGroup.GET("/ops/script/info", ctl.GetOpsScriptInfo)
		authGroup.POST("/ops/script/add", ctl.CreateOpsScript)
		authGroup.PUT("/ops/script/update", ctl.UpdateOpsScript)
		authGroup.PUT("/ops/script/status", ctl.UpdateOpsScriptStatus)
		authGroup.GET("/ops/script/versions", ctl.GetOpsScriptVersions)
		authGroup.POST("/ops/script/rollback", ctl.RollbackOpsScript)
		authGroup.DELETE("/ops/script/delete", ctl.DeleteOpsScript)
		authGroup.POST("/ops/exec/command", ctl.ExecuteOpsCommand)
		authGroup.POST("/ops/exec/script", ctl.ExecuteOpsScript)
		authGroup.POST("/ops/exec/file-dispatch", ctl.ExecuteOpsFileDispatch)
		authGroup.GET("/ops/exec/history", ctl.GetOpsExecTaskList)
		authGroup.GET("/ops/exec/history/detail", ctl.GetOpsExecTaskDetail)
		authGroup.POST("/ops/exec/retry", ctl.RetryOpsExecTask)
		authGroup.GET("/ops/schedule/task/list", ctl.GetOpsScheduleTaskList)
		authGroup.GET("/ops/schedule/task/info", ctl.GetOpsScheduleTaskInfo)
		authGroup.POST("/ops/schedule/task/add", ctl.CreateOpsScheduleTask)
		authGroup.PUT("/ops/schedule/task/update", ctl.UpdateOpsScheduleTask)
		authGroup.PUT("/ops/schedule/task/status", ctl.UpdateOpsScheduleTaskStatus)
		authGroup.POST("/ops/schedule/task/run", ctl.RunOpsScheduleTask)
		authGroup.DELETE("/ops/schedule/task/delete", ctl.DeleteOpsScheduleTask)
		authGroup.DELETE("/ops/schedule/task/batch/delete", ctl.BatchDeleteOpsScheduleTask)
		authGroup.GET("/ops/schedule/log/list", ctl.GetOpsScheduleLogList)
		authGroup.GET("/ops/schedule/log/info", ctl.GetOpsScheduleLogInfo)
		authGroup.GET("/ops/schedule/template/list", ctl.GetOpsScheduleTemplateList)
		authGroup.GET("/ops/schedule/template/info", ctl.GetOpsScheduleTemplateInfo)
		authGroup.POST("/ops/schedule/template/add", ctl.CreateOpsScheduleTemplate)
		authGroup.PUT("/ops/schedule/template/update", ctl.UpdateOpsScheduleTemplate)
		authGroup.DELETE("/ops/schedule/template/delete", ctl.DeleteOpsScheduleTemplate)
		authGroup.GET("/ops/job/list", ctl.GetOpsJobList)
		authGroup.GET("/ops/job/info", ctl.GetOpsJobInfo)
		authGroup.POST("/ops/job/add", ctl.CreateOpsJob)
		authGroup.PUT("/ops/job/update", ctl.UpdateOpsJob)
		authGroup.POST("/ops/job/run", ctl.RunOpsJob)
		authGroup.PUT("/ops/job/status", ctl.UpdateOpsJobStatus)
		authGroup.DELETE("/ops/job/delete", ctl.DeleteOpsJob)
		authGroup.GET("/ops/job/history/list", ctl.GetOpsJobHistoryList)
		authGroup.GET("/ops/job/history/detail", ctl.GetOpsJobHistoryDetail)
		authGroup.POST("/ops/job/history/approve", ctl.ApproveOpsJobHistory)
		authGroup.POST("/ops/job/history/reject", ctl.RejectOpsJobHistory)
		authGroup.GET("/ops/job/template/list", ctl.GetOpsJobTemplateList)
		authGroup.GET("/ops/job/template/options", ctl.GetOpsJobTemplateOptions)
		authGroup.GET("/ops/job/template/info", ctl.GetOpsJobTemplateInfo)
		authGroup.POST("/ops/job/template/add", ctl.CreateOpsJobTemplate)
		authGroup.PUT("/ops/job/template/update", ctl.UpdateOpsJobTemplate)
		authGroup.PUT("/ops/job/template/status", ctl.UpdateOpsJobTemplateStatus)
		authGroup.DELETE("/ops/job/template/delete", ctl.DeleteOpsJobTemplate)
		authGroup.GET("/ops/environment/list", ctl.GetOpsEnvironmentList)
		authGroup.POST("/ops/environment/save", ctl.SaveOpsEnvironment)
		authGroup.DELETE("/ops/environment/delete", ctl.DeleteOpsEnvironment)
		authGroup.GET("/ops/application/list", ctl.GetOpsApplicationList)
		authGroup.GET("/ops/application/options", ctl.GetOpsApplicationOptions)
		authGroup.GET("/ops/application/info", ctl.GetOpsApplicationInfo)
		authGroup.GET("/ops/application/bindings", ctl.GetOpsApplicationBindings)
		authGroup.POST("/ops/application/save", ctl.SaveOpsApplication)
		authGroup.DELETE("/ops/application/delete", ctl.DeleteOpsApplication)
		authGroup.GET("/ops/application/build-task/list", ctl.GetOpsAppBuildTaskList)
		authGroup.GET("/ops/application/build-task/info", ctl.GetOpsAppBuildTaskInfo)
		authGroup.POST("/ops/application/build-task/save", ctl.SaveOpsAppBuildTask)
		authGroup.PUT("/ops/application/build-task/status", ctl.UpdateOpsAppBuildTaskStatus)
		authGroup.DELETE("/ops/application/build-task/delete", ctl.DeleteOpsAppBuildTask)
		authGroup.POST("/ops/application/build-task/run", ctl.RunOpsAppBuildTask)
		authGroup.POST("/ops/application/release/run", ctl.RunOpsAppRelease)
		authGroup.POST("/ops/application/release/retry", ctl.RetryOpsAppRelease)
		authGroup.GET("/ops/application/release/list", ctl.GetOpsAppReleaseList)
		authGroup.GET("/ops/application/release/info", ctl.GetOpsAppReleaseInfo)
		authGroup.GET("/ops/application/artifact/list", ctl.GetOpsAppArtifactList)
		authGroup.GET("/ops/application/image-registry/list", ctl.GetOpsImageRegistryList)
		authGroup.POST("/ops/application/image-registry/save", ctl.SaveOpsImageRegistry)
		authGroup.DELETE("/ops/application/image-registry/delete", ctl.DeleteOpsImageRegistry)
		authGroup.GET("/ops/application/pipeline/template/list", ctl.GetOpsAppPipelineTemplateList)
		authGroup.GET("/ops/application/pipeline/list", ctl.GetOpsAppPipelineList)
		authGroup.GET("/ops/application/pipeline/info", ctl.GetOpsAppPipelineInfo)
		authGroup.POST("/ops/application/pipeline/save", ctl.SaveOpsAppPipeline)
		authGroup.PUT("/ops/application/pipeline/status", ctl.UpdateOpsAppPipelineStatus)
		authGroup.DELETE("/ops/application/pipeline/delete", ctl.DeleteOpsAppPipeline)
		authGroup.POST("/ops/application/pipeline/copy", ctl.CopyOpsAppPipeline)
		authGroup.POST("/ops/application/pipeline/run", ctl.RunOpsAppPipeline)
		authGroup.GET("/ops/application/pipeline/run/list", ctl.GetOpsAppPipelineRunList)
		authGroup.GET("/ops/application/pipeline/run/info", ctl.GetOpsAppPipelineRunInfo)
		authGroup.POST("/ops/application/pipeline/run/approve", ctl.ApproveOpsAppPipelineRun)
		authGroup.POST("/ops/application/pipeline/run/rollback", ctl.RollbackOpsAppPipelineRun)

		authGroup.GET("/notify/template/list", ctl.GetNotifyTemplateList)
		authGroup.GET("/notify/template/options", ctl.GetNotifyTemplateOptions)
		authGroup.GET("/notify/template/info", ctl.GetNotifyTemplateInfo)
		authGroup.POST("/notify/template/save", ctl.SaveNotifyTemplate)
		authGroup.DELETE("/notify/template/delete", ctl.DeleteNotifyTemplate)
		authGroup.GET("/notify/channel/list", ctl.GetNotifyChannelList)
		authGroup.GET("/notify/channel/options", ctl.GetNotifyChannelOptions)
		authGroup.GET("/notify/channel/info", ctl.GetNotifyChannelInfo)
		authGroup.POST("/notify/channel/save", ctl.SaveNotifyChannel)
		authGroup.DELETE("/notify/channel/delete", ctl.DeleteNotifyChannel)
		authGroup.GET("/notify/rule/list", ctl.GetNotifyRuleList)
		authGroup.GET("/notify/rule/options", ctl.GetNotifyRuleOptions)
		authGroup.GET("/notify/rule/info", ctl.GetNotifyRuleInfo)
		authGroup.POST("/notify/rule/save", ctl.SaveNotifyRule)
		authGroup.POST("/notify/rule/test", ctl.TestNotifyRule)
		authGroup.DELETE("/notify/rule/delete", ctl.DeleteNotifyRule)
		authGroup.GET("/notify/send-log/list", ctl.GetNotifySendLogList)
		authGroup.POST("/notify/send-log/retry", ctl.RetryNotifySendLog)

		authGroup.GET("/monitor/overview", ctl.GetMonitorOverview)
		authGroup.GET("/monitor/command-center", ctl.GetMonitorCommandCenter)
		authGroup.GET("/monitor/datasource/list", ctl.GetMonitorDatasourceList)
		authGroup.GET("/monitor/datasource/options", ctl.GetMonitorDatasourceOptions)
		authGroup.GET("/monitor/datasource/info", ctl.GetMonitorDatasourceInfo)
		authGroup.POST("/monitor/datasource/save", ctl.SaveMonitorDatasource)
		authGroup.DELETE("/monitor/datasource/delete", ctl.DeleteMonitorDatasource)
		authGroup.POST("/monitor/datasource/test", ctl.TestMonitorDatasource)
		authGroup.POST("/monitor/query/instant", ctl.QueryMonitorPrometheus)
		authGroup.POST("/monitor/query/range", ctl.QueryMonitorPrometheusRange)
		authGroup.POST("/monitor/logs/query", ctl.QueryMonitorLogs)
		authGroup.GET("/monitor/logs/indices", ctl.GetMonitorElasticsearchIndices)
		authGroup.GET("/monitor/logs/streams", ctl.GetMonitorVictoriaLogsStreams)
		authGroup.GET("/monitor/logs/fields", ctl.GetMonitorLogFields)
		authGroup.GET("/monitor/logs/field-values", ctl.GetMonitorLogFieldValues)
		authGroup.GET("/monitor/logs/shortcuts", ctl.GetMonitorLogShortcuts)
		authGroup.POST("/monitor/logs/shortcuts/save", ctl.SaveMonitorLogShortcut)
		authGroup.DELETE("/monitor/logs/shortcuts/delete", ctl.DeleteMonitorLogShortcut)
		authGroup.GET("/monitor/traces/services", ctl.GetMonitorJaegerServices)
		authGroup.GET("/monitor/traces/operations", ctl.GetMonitorJaegerOperations)
		authGroup.POST("/monitor/traces/query", ctl.QueryMonitorTraces)
		authGroup.GET("/monitor/traces/detail", ctl.GetMonitorTrace)
		authGroup.GET("/monitor/query/history", ctl.GetMonitorQueryHistoryList)
		authGroup.GET("/monitor/alert/template/list", ctl.GetMonitorAlertTemplateList)
		authGroup.GET("/monitor/alert/template/groups", ctl.GetMonitorAlertTemplateGroups)
		authGroup.POST("/monitor/alert/template/group/save", ctl.SaveMonitorAlertTemplateGroup)
		authGroup.DELETE("/monitor/alert/template/group/delete", ctl.DeleteMonitorAlertTemplateGroup)
		authGroup.GET("/monitor/alert/template/info", ctl.GetMonitorAlertTemplateInfo)
		authGroup.POST("/monitor/alert/template/save", ctl.SaveMonitorAlertTemplate)
		authGroup.DELETE("/monitor/alert/template/delete", ctl.DeleteMonitorAlertTemplate)
		authGroup.POST("/monitor/alert/template/prometheus/parse", ctl.ParsePrometheusAlertTemplates)
		authGroup.POST("/monitor/alert/template/prometheus/import", ctl.ImportPrometheusAlertTemplates)
		authGroup.POST("/monitor/alert/template/prometheus/export", ctl.ExportPrometheusAlertTemplates)
		authGroup.GET("/monitor/alert/rule/list", ctl.GetMonitorAlertRuleList)
		authGroup.GET("/monitor/alert/rule/info", ctl.GetMonitorAlertRuleInfo)
		authGroup.POST("/monitor/alert/rule/save", ctl.SaveMonitorAlertRule)
		authGroup.DELETE("/monitor/alert/rule/delete", ctl.DeleteMonitorAlertRule)
		authGroup.PUT("/monitor/alert/rule/status", ctl.UpdateMonitorAlertRuleStatus)
		authGroup.POST("/monitor/alert/rule/batch", ctl.BatchUpdateMonitorAlertRules)
		authGroup.POST("/monitor/alert/rule/run", ctl.RunMonitorAlertRule)
		authGroup.POST("/monitor/alert/rule/preview", ctl.PreviewMonitorAlertRule)
		authGroup.GET("/monitor/silence/rule/list", ctl.GetMonitorSilenceRuleList)
		authGroup.GET("/monitor/silence/rule/info", ctl.GetMonitorSilenceRuleInfo)
		authGroup.POST("/monitor/silence/rule/save", ctl.SaveMonitorSilenceRule)
		authGroup.POST("/monitor/silence/rule/preview", ctl.PreviewMonitorSilenceRule)
		authGroup.DELETE("/monitor/silence/rule/delete", ctl.DeleteMonitorSilenceRule)
		authGroup.POST("/monitor/silence/rule/batch", ctl.BatchUpdateMonitorSilenceRules)
		authGroup.GET("/monitor/aggregation/rule/list", ctl.GetMonitorAggregationRuleList)
		authGroup.GET("/monitor/aggregation/rule/info", ctl.GetMonitorAggregationRuleInfo)
		authGroup.POST("/monitor/aggregation/rule/save", ctl.SaveMonitorAggregationRule)
		authGroup.DELETE("/monitor/aggregation/rule/delete", ctl.DeleteMonitorAggregationRule)
		authGroup.POST("/monitor/aggregation/rule/batch", ctl.BatchUpdateMonitorAggregationRules)
		authGroup.GET("/monitor/alert/event/list", ctl.GetMonitorAlertEventList)
		authGroup.GET("/monitor/alert/event/detail", ctl.GetMonitorAlertEventDetail)
		authGroup.POST("/monitor/alert/event/claim", ctl.ClaimMonitorAlertEvent)
		authGroup.POST("/monitor/alert/event/resolve", ctl.ResolveMonitorAlertEvent)
		authGroup.POST("/monitor/alert/event/batch", ctl.BatchUpdateMonitorAlertEvents)
		authGroup.POST("/monitor/alert/event/action", ctl.TriggerMonitorAlertAction)
		authGroup.GET("/monitor/dashboard/list", ctl.GetMonitorDashboardList)
		authGroup.GET("/monitor/dashboard/info", ctl.GetMonitorDashboardInfo)
		authGroup.POST("/monitor/dashboard/save", ctl.SaveMonitorDashboard)
		authGroup.DELETE("/monitor/dashboard/delete", ctl.DeleteMonitorDashboard)
		authGroup.POST("/monitor/dashboard/panel/save", ctl.SaveMonitorDashboardPanel)
		authGroup.DELETE("/monitor/dashboard/panel/delete", ctl.DeleteMonitorDashboardPanel)
		authGroup.POST("/monitor/dashboard/panel/query", ctl.QueryMonitorDashboardPanel)
		authGroup.GET("/k8s/cluster/list", ctl.GetK8sClusterList)
		authGroup.GET("/k8s/cluster/info", ctl.GetK8sClusterInfo)
		authGroup.POST("/k8s/cluster/add", ctl.CreateK8sCluster)
		authGroup.PUT("/k8s/cluster/update", ctl.UpdateK8sCluster)
		authGroup.DELETE("/k8s/cluster/delete", ctl.DeleteK8sCluster)
		authGroup.GET("/k8s/cluster/detail", ctl.GetK8sClusterDetail)
		authGroup.GET("/k8s/node/detail", ctl.GetK8sNodeDetail)
		authGroup.GET("/k8s/node/pods", ctl.GetK8sNodePods)
		authGroup.PUT("/k8s/node/labels", ctl.UpdateK8sNodeLabels)
		authGroup.GET("/k8s/namespace/detail", ctl.GetK8sNamespaceDetail)
		authGroup.GET("/k8s/namespace/events", ctl.GetK8sNamespaceEvents)
		authGroup.GET("/k8s/service/detail", ctl.GetK8sServiceDetail)
		authGroup.PUT("/k8s/service/update", ctl.UpdateK8sService)
		authGroup.GET("/k8s/ingress/detail", ctl.GetK8sIngressDetail)
		authGroup.GET("/k8s/istio/detail", ctl.GetK8sIstioResourceDetail)
		authGroup.GET("/k8s/configmap/detail", ctl.GetK8sConfigMapDetail)
		authGroup.GET("/k8s/secret/detail", ctl.GetK8sSecretDetail)
		authGroup.GET("/k8s/storage/detail", ctl.GetK8sStorageDetail)
		authGroup.GET("/k8s/pod/detail", ctl.GetK8sPodDetail)
		authGroup.GET("/k8s/pod/metrics", ctl.GetK8sPodMetrics)
		authGroup.GET("/k8s/workload/metrics", ctl.GetK8sWorkloadMetrics)
		authGroup.GET("/k8s/pod/containers", ctl.GetK8sPodContainers)
		authGroup.GET("/k8s/pod/logs", ctl.GetK8sPodLogs)
		authGroup.GET("/k8s/pod/events", ctl.GetK8sPodEvents)
		authGroup.GET("/k8s/workload/detail", ctl.GetK8sWorkloadDetail)
		authGroup.POST("/k8s/workload/scale", ctl.ScaleK8sWorkload)
		authGroup.POST("/k8s/workload/restart", ctl.RestartK8sWorkload)
		authGroup.POST("/k8s/workload/images", ctl.UpdateK8sWorkloadImages)
		authGroup.PUT("/k8s/workload/resources", ctl.UpdateK8sWorkloadResources)
		authGroup.POST("/k8s/workload/create", ctl.CreateK8sWorkloadBundle)
		authGroup.POST("/k8s/istio/traffic", ctl.UpdateK8sIstioTraffic)
		authGroup.POST("/k8s/httproute/traffic", ctl.UpdateK8sHTTPRouteTraffic)
		authGroup.POST("/k8s/resource/yaml/create", ctl.CreateK8sResourceYAML)
		authGroup.PUT("/k8s/resource/yaml", ctl.UpdateK8sResourceYAML)
		authGroup.DELETE("/k8s/resource/delete", ctl.DeleteK8sResource)
	}

	return engine, svc
}
