import http from './http'

export const queryAssetOverview = () => http.get('/api/v1/asset/overview')
export const queryAssetServiceList = (params) => http.get('/api/v1/asset/service/list', { params })
export const assetServiceInfo = (id) => http.get('/api/v1/asset/service/info', { params: { id } })
export const saveAssetService = (data) => http.post('/api/v1/asset/service/save', data)
export const deleteAssetService = (id) => http.delete('/api/v1/asset/service/delete', { data: { id } })
export const queryAssetServiceK8sCatalog = (params) => http.get('/api/v1/asset/service/k8s/catalog', { params })
export const queryAssetServiceRuntimeTopology = (serviceId) => http.get('/api/v1/asset/service/runtime-topology', { params: { serviceId } })
export const queryAssetServiceWorkloadRuntime = (params) => http.get('/api/v1/asset/service/workload/runtime', { params })
export const queryAssetServiceWorkloadTopology = (params) => http.get('/api/v1/asset/service/workload/topology', { params })
export const queryAssetServiceWorkloadMetrics = (params) => http.get('/api/v1/asset/service/workload/metrics', { params })
export const queryAssetServiceWorkloadRolloutHistory = (params) => http.get('/api/v1/asset/service/workload/rollout-history', { params })
export const rollbackAssetServiceWorkload = (data) => http.post('/api/v1/asset/service/workload/rollback', data)
export const queryAssetServiceWorkloadLogs = (params) => http.get('/api/v1/asset/service/workload/logs', { params })
export const queryAssetServiceDiagnosisProcesses = (params) => http.get('/api/v1/asset/service/diagnosis/processes', { params, timeout: 30000 })
export const queryAssetServiceDiagnosisEnvironment = (params) => http.get('/api/v1/asset/service/diagnosis/environment', { params, timeout: 30000 })
export const queryAssetServiceDiagnosisRun = (params) => http.get('/api/v1/asset/service/diagnosis/run', { params, timeout: 240000 })
export const downloadAssetServiceArthas = (data) => http.post('/api/v1/asset/service/diagnosis/arthas/download', data, { timeout: 120000 })
export const uploadAssetServiceArthas = (data) => http.post('/api/v1/asset/service/diagnosis/arthas/upload', data, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 120000 })
export const queryAssetChangeLogs = (params) => http.get('/api/v1/asset/change-log/list', { params })
export const queryAssetHostList = (params) => http.get('/api/v1/asset/host/list', { params })
export const assetHostInfo = (id) => http.get('/api/v1/asset/host/info', { params: { id } })
export const queryAssetHostMetrics = (params) => http.get('/api/v1/asset/host/metrics', { params })
export const downloadAssetHostTemplate = () => http.get('/api/v1/asset/host/template', { responseType: 'blob' })
export const addAssetHost = (data) => http.post('/api/v1/asset/host/add', data)
export const importAssetHosts = (data) =>
  http.post('/api/v1/asset/host/import', data, {
    headers: { 'Content-Type': 'multipart/form-data' }
  })
export const updateAssetHost = (data) => http.put('/api/v1/asset/host/update', data)
export const syncAssetHostsFromCloud = (data) => http.post('/api/v1/asset/host/cloudSync', data)
export const syncAssetHost = (id) => http.post('/api/v1/asset/host/sync', { id })
export const deleteAssetHost = (id) => http.delete('/api/v1/asset/host/delete', { data: { id } })
// SSH connectivity and host-information collection can exceed the global 15-second timeout.
export const batchSyncAssetHosts = (ids) => http.post('/api/v1/asset/host/batch/sync', { ids }, { timeout: 60000 })
export const batchDeleteAssetHosts = (ids) => http.delete('/api/v1/asset/host/batch/delete', { data: { ids } })
export const batchReplaceAssetHostCredential = (data) => http.put('/api/v1/asset/host/batch/credential', data)
export const removeAssetHostsFromGroup = (data) => http.delete('/api/v1/asset/host/group/remove', { data })
export const uploadAssetTerminalFile = (data, onUploadProgress) => http.post('/api/v1/asset/terminal/upload', data, { headers: { 'Content-Type': 'multipart/form-data' }, timeout: 10 * 60 * 1000, onUploadProgress })
export const downloadAssetTerminalFile = (hostId, path) => http.get('/api/v1/asset/terminal/download', { params: { hostId, path }, responseType: 'blob', timeout: 10 * 60 * 1000 })
export const queryAssetTerminalFiles = (hostId, path) => http.get('/api/v1/asset/terminal/files', { params: { hostId, path }, timeout: 60000 })

export const queryAssetHostGroupList = (params) => http.get('/api/v1/asset/hostGroup/list', { params })
export const assetHostGroupInfo = (id) => http.get('/api/v1/asset/hostGroup/info', { params: { id } })
export const addAssetHostGroup = (data) => http.post('/api/v1/asset/hostGroup/add', data)
export const updateAssetHostGroup = (data) => http.put('/api/v1/asset/hostGroup/update', data)
export const deleteAssetHostGroup = (id) => http.delete('/api/v1/asset/hostGroup/delete', { data: { id } })

export const queryAssetCredentialList = (params) => http.get('/api/v1/asset/credential/list', { params })
export const queryAssetCredentialOptions = () => http.get('/api/v1/asset/credential/options')
export const assetCredentialInfo = (id) => http.get('/api/v1/asset/credential/info', { params: { id } })
export const addAssetCredential = (data) => http.post('/api/v1/asset/credential/add', data)
export const updateAssetCredential = (data) => http.put('/api/v1/asset/credential/update', data)
export const deleteAssetCredential = (id) => http.delete('/api/v1/asset/credential/delete', { data: { id } })

export const queryAssetCloudAccountList = (params) => http.get('/api/v1/asset/cloudAccount/list', { params })
export const queryAssetCloudAccountOptions = () => http.get('/api/v1/asset/cloudAccount/options')
export const assetCloudAccountInfo = (id) => http.get('/api/v1/asset/cloudAccount/info', { params: { id } })
export const addAssetCloudAccount = (data) => http.post('/api/v1/asset/cloudAccount/add', data)
export const updateAssetCloudAccount = (data) => http.put('/api/v1/asset/cloudAccount/update', data)
export const deleteAssetCloudAccount = (id) => http.delete('/api/v1/asset/cloudAccount/delete', { data: { id } })

export const queryAssetGatewayList = (params) => http.get('/api/v1/asset/gateway/list', { params })
export const queryAssetGatewayOptions = () => http.get('/api/v1/asset/gateway/options')
export const assetGatewayInfo = (id) => http.get('/api/v1/asset/gateway/info', { params: { id } })
export const addAssetGateway = (data) => http.post('/api/v1/asset/gateway/add', data)
export const updateAssetGateway = (data) => http.put('/api/v1/asset/gateway/update', data)
export const deleteAssetGateway = (id) => http.delete('/api/v1/asset/gateway/delete', { data: { id } })
export const updateAssetGatewayStatus = (data) => http.put('/api/v1/asset/gateway/status', data)
export const testAssetGateway = (id) => http.post('/api/v1/asset/gateway/test', { id })

export const queryAssetDatabaseList = (params) => http.get('/api/v1/asset/database/list', { params })
export const assetDatabaseInfo = (id) => http.get('/api/v1/asset/database/info', { params: { id } })
export const queryAssetDatabaseMetrics = (params) => http.get('/api/v1/asset/database/metrics', { params })
export const addAssetDatabase = (data) => http.post('/api/v1/asset/database/add', data)
export const updateAssetDatabase = (data) => http.put('/api/v1/asset/database/update', data)
export const deleteAssetDatabase = (id) => http.delete('/api/v1/asset/database/delete', { data: { id } })
export const testAssetDatabase = (data) => http.post('/api/v1/asset/database/test', data)
