import http from './http'

export const queryMonitorOverview = (params = {}) => http.get('/api/v1/monitor/overview', { params })
export const queryMonitorCommandCenter = () => http.get('/api/v1/monitor/command-center')

export const queryMonitorDatasourceList = (params) => http.get('/api/v1/monitor/datasource/list', { params })
export const queryMonitorDatasourceOptions = () => http.get('/api/v1/monitor/datasource/options')
export const monitorDatasourceInfo = (id) => http.get('/api/v1/monitor/datasource/info', { params: { id } })
export const saveMonitorDatasource = (data) => http.post('/api/v1/monitor/datasource/save', data)
export const deleteMonitorDatasource = (id) => http.delete('/api/v1/monitor/datasource/delete', { data: { id } })
export const testMonitorDatasource = (data) => http.post('/api/v1/monitor/datasource/test', data, { params: { id: data.id || 0 } })

export const queryMonitorPrometheus = (data) => http.post('/api/v1/monitor/query/instant', data)
export const queryMonitorPrometheusRange = (data) => http.post('/api/v1/monitor/query/range', data)
export const queryMonitorLogs = (data) => http.post('/api/v1/monitor/logs/query', data)
export const queryMonitorElasticsearchIndices = (params) => http.get('/api/v1/monitor/logs/indices', { params })
export const queryMonitorVictoriaLogsStreams = (params) => http.get('/api/v1/monitor/logs/streams', { params })
export const queryMonitorLogFields = (params) => http.get('/api/v1/monitor/logs/fields', { params })
export const queryMonitorLogFieldValues = (params) => http.get('/api/v1/monitor/logs/field-values', { params })
export const queryMonitorLogShortcuts = (params) => http.get('/api/v1/monitor/logs/shortcuts', { params })
export const saveMonitorLogShortcut = (data) => http.post('/api/v1/monitor/logs/shortcuts/save', data)
export const deleteMonitorLogShortcut = (id) => http.delete('/api/v1/monitor/logs/shortcuts/delete', { data: { id } })
export const queryMonitorJaegerServices = (params) => http.get('/api/v1/monitor/traces/services', { params })
export const queryMonitorJaegerOperations = (params) => http.get('/api/v1/monitor/traces/operations', { params })
export const queryMonitorTraces = (data) => http.post('/api/v1/monitor/traces/query', data)
export const queryMonitorTraceDetail = (params) => http.get('/api/v1/monitor/traces/detail', { params })
export const queryMonitorQueryHistoryList = (params) => http.get('/api/v1/monitor/query/history', { params })

export const queryMonitorAlertTemplateList = (params) => http.get('/api/v1/monitor/alert/template/list', { params })
export const queryMonitorAlertTemplateGroups = () => http.get('/api/v1/monitor/alert/template/groups')
export const saveMonitorAlertTemplateGroup = (data) => http.post('/api/v1/monitor/alert/template/group/save', data)
export const deleteMonitorAlertTemplateGroup = (id) => http.delete('/api/v1/monitor/alert/template/group/delete', { data: { id } })
export const monitorAlertTemplateInfo = (id) => http.get('/api/v1/monitor/alert/template/info', { params: { id } })
export const saveMonitorAlertTemplate = (data) => http.post('/api/v1/monitor/alert/template/save', data)
export const deleteMonitorAlertTemplate = (id) => http.delete('/api/v1/monitor/alert/template/delete', { data: { id } })
export const parsePrometheusAlertTemplates = (content) => http.post('/api/v1/monitor/alert/template/prometheus/parse', { content })
export const importPrometheusAlertTemplates = (data) => http.post('/api/v1/monitor/alert/template/prometheus/import', data)
export const exportPrometheusAlertTemplates = (ids) => http.post('/api/v1/monitor/alert/template/prometheus/export', { ids }, { responseType: 'blob' })

export const queryMonitorAlertRuleList = (params) => http.get('/api/v1/monitor/alert/rule/list', { params })
export const monitorAlertRuleInfo = (id) => http.get('/api/v1/monitor/alert/rule/info', { params: { id } })
export const saveMonitorAlertRule = (data) => http.post('/api/v1/monitor/alert/rule/save', data)
export const deleteMonitorAlertRule = (id) => http.delete('/api/v1/monitor/alert/rule/delete', { data: { id } })
export const updateMonitorAlertRuleStatus = (data) => http.put('/api/v1/monitor/alert/rule/status', data)
export const batchUpdateMonitorAlertRules = (data) => http.post('/api/v1/monitor/alert/rule/batch', data)
export const runMonitorAlertRule = (id) => http.post('/api/v1/monitor/alert/rule/run', { id })
export const previewMonitorAlertRule = (data) => http.post('/api/v1/monitor/alert/rule/preview', data)

export const queryMonitorSilenceRuleList = (params) => http.get('/api/v1/monitor/silence/rule/list', { params })
export const monitorSilenceRuleInfo = (id) => http.get('/api/v1/monitor/silence/rule/info', { params: { id } })
export const saveMonitorSilenceRule = (data) => http.post('/api/v1/monitor/silence/rule/save', data)
export const previewMonitorSilenceRule = (data) => http.post('/api/v1/monitor/silence/rule/preview', data)
export const deleteMonitorSilenceRule = (id) => http.delete('/api/v1/monitor/silence/rule/delete', { data: { id } })
export const batchUpdateMonitorSilenceRules = (data) => http.post('/api/v1/monitor/silence/rule/batch', data)

export const queryMonitorAggregationRuleList = (params) => http.get('/api/v1/monitor/aggregation/rule/list', { params })
export const monitorAggregationRuleInfo = (id) => http.get('/api/v1/monitor/aggregation/rule/info', { params: { id } })
export const saveMonitorAggregationRule = (data) => http.post('/api/v1/monitor/aggregation/rule/save', data)
export const deleteMonitorAggregationRule = (id) => http.delete('/api/v1/monitor/aggregation/rule/delete', { data: { id } })
export const batchUpdateMonitorAggregationRules = (data) => http.post('/api/v1/monitor/aggregation/rule/batch', data)

export const queryMonitorAlertEventList = (params) => http.get('/api/v1/monitor/alert/event/list', { params })
export const queryMonitorAlertEventDetail = (id) => http.get('/api/v1/monitor/alert/event/detail', { params: { id } })
export const claimMonitorAlertEvent = (data) => http.post('/api/v1/monitor/alert/event/claim', data)
export const resolveMonitorAlertEvent = (data) => http.post('/api/v1/monitor/alert/event/resolve', data)
export const batchUpdateMonitorAlertEvents = (data) => http.post('/api/v1/monitor/alert/event/batch', data)
export const triggerMonitorAlertAction = (data) => http.post('/api/v1/monitor/alert/event/action', data)

export const queryMonitorDashboardList = (params) => http.get('/api/v1/monitor/dashboard/list', { params })
export const monitorDashboardInfo = (id) => http.get('/api/v1/monitor/dashboard/info', { params: { id } })
export const saveMonitorDashboard = (data) => http.post('/api/v1/monitor/dashboard/save', data)
export const deleteMonitorDashboard = (id) => http.delete('/api/v1/monitor/dashboard/delete', { data: { id } })
export const saveMonitorDashboardPanel = (data) => http.post('/api/v1/monitor/dashboard/panel/save', data)
export const deleteMonitorDashboardPanel = (id) => http.delete('/api/v1/monitor/dashboard/panel/delete', { data: { id } })
export const queryMonitorDashboardPanel = (payload) => http.post('/api/v1/monitor/dashboard/panel/query', typeof payload === 'object' ? payload : { id: payload })
export const runMonitorInspection = (data) => http.post('/api/v1/monitor/inspection/run', data)
export const queryLatestMonitorInspectionRun = (dashboardId) => http.get('/api/v1/monitor/inspection/run/latest', { params: { dashboardId } })
export const monitorInspectionRunInfo = (id) => http.get('/api/v1/monitor/inspection/run/info', { params: { id } })
