import http from './http'

export const queryOpsScriptList = (params) => http.get('/api/v1/ops/script/list', { params })
export const queryOpsScriptOptions = () => http.get('/api/v1/ops/script/options')
export const opsScriptInfo = (id) => http.get('/api/v1/ops/script/info', { params: { id } })
export const addOpsScript = (data) => http.post('/api/v1/ops/script/add', data)
export const updateOpsScript = (data) => http.put('/api/v1/ops/script/update', data)
export const updateOpsScriptStatus = (data) => http.put('/api/v1/ops/script/status', data)
export const deleteOpsScript = (id) => http.delete('/api/v1/ops/script/delete', { data: { id } })
export const queryOpsScriptVersions = (id) => http.get('/api/v1/ops/script/versions', { params: { id } })
export const rollbackOpsScript = (data) => http.post('/api/v1/ops/script/rollback', data)

export const executeOpsCommand = (data) => http.post('/api/v1/ops/exec/command', data)
export const executeOpsScript = (data) => http.post('/api/v1/ops/exec/script', data)
export const executeOpsFileDispatch = (data) =>
  http.post('/api/v1/ops/exec/file-dispatch', data, {
    headers: { 'Content-Type': 'multipart/form-data' },
    timeout: 600000
  })

export const queryOpsExecHistory = (params) => http.get('/api/v1/ops/exec/history', { params })
export const queryOpsExecHistoryDetail = (id) => http.get('/api/v1/ops/exec/history/detail', { params: { id } })
export const retryOpsExecTask = (taskId) => http.post('/api/v1/ops/exec/retry', { taskId })

export const queryOpsScheduleTaskList = (params) => http.get('/api/v1/ops/schedule/task/list', { params })
export const opsScheduleTaskInfo = (id) => http.get('/api/v1/ops/schedule/task/info', { params: { id } })
export const addOpsScheduleTask = (data) => http.post('/api/v1/ops/schedule/task/add', data)
export const updateOpsScheduleTask = (data) => http.put('/api/v1/ops/schedule/task/update', data)
export const updateOpsScheduleTaskStatus = (data) => http.put('/api/v1/ops/schedule/task/status', data)
export const runOpsScheduleTask = (id) => http.post('/api/v1/ops/schedule/task/run', { id })
export const previewOpsScheduleTaskNotification = (data) => http.post('/api/v1/ops/schedule/task/notify-preview', data)
export const deleteOpsScheduleTask = (id) => http.delete('/api/v1/ops/schedule/task/delete', { data: { id } })
export const batchDeleteOpsScheduleTask = (ids) => http.delete('/api/v1/ops/schedule/task/batch/delete', { data: { ids } })

export const queryOpsScheduleLogList = (params) => http.get('/api/v1/ops/schedule/log/list', { params })
export const opsScheduleLogInfo = (id) => http.get('/api/v1/ops/schedule/log/info', { params: { id } })

export const queryOpsScheduleTemplateList = (params) => http.get('/api/v1/ops/schedule/template/list', { params })
export const opsScheduleTemplateInfo = (id) => http.get('/api/v1/ops/schedule/template/info', { params: { id } })
export const addOpsScheduleTemplate = (data) => http.post('/api/v1/ops/schedule/template/add', data)
export const updateOpsScheduleTemplate = (data) => http.put('/api/v1/ops/schedule/template/update', data)
export const deleteOpsScheduleTemplate = (id) => http.delete('/api/v1/ops/schedule/template/delete', { data: { id } })

export const queryOpsJobList = (params) => http.get('/api/v1/ops/job/list', { params })
export const opsJobInfo = (id) => http.get('/api/v1/ops/job/info', { params: { id } })
export const addOpsJob = (data) => http.post('/api/v1/ops/job/add', data)
export const updateOpsJob = (data) => http.put('/api/v1/ops/job/update', data)
export const updateOpsJobStatus = (data) => http.put('/api/v1/ops/job/status', data)
export const runOpsJob = (id) => http.post('/api/v1/ops/job/run', { id })
export const deleteOpsJob = (id) => http.delete('/api/v1/ops/job/delete', { data: { id } })

export const queryOpsJobHistoryList = (params) => http.get('/api/v1/ops/job/history/list', { params })
export const opsJobHistoryDetail = (id) => http.get('/api/v1/ops/job/history/detail', { params: { id } })
export const approveOpsJobHistory = (data) => http.post('/api/v1/ops/job/history/approve', data)
export const rejectOpsJobHistory = (data) => http.post('/api/v1/ops/job/history/reject', data)

export const queryOpsJobTemplateList = (params) => http.get('/api/v1/ops/job/template/list', { params })
export const queryOpsJobTemplateOptions = () => http.get('/api/v1/ops/job/template/options')
export const opsJobTemplateInfo = (id) => http.get('/api/v1/ops/job/template/info', { params: { id } })
export const addOpsJobTemplate = (data) => http.post('/api/v1/ops/job/template/add', data)
export const updateOpsJobTemplate = (data) => http.put('/api/v1/ops/job/template/update', data)
export const updateOpsJobTemplateStatus = (data) => http.put('/api/v1/ops/job/template/status', data)
export const deleteOpsJobTemplate = (id) => http.delete('/api/v1/ops/job/template/delete', { data: { id } })

export const queryOpsApplicationList = (params) => http.get('/api/v1/ops/application/list', { params })
export const queryOpsApplicationOptions = () => http.get('/api/v1/ops/application/options')
export const opsApplicationInfo = (id) => http.get('/api/v1/ops/application/info', { params: { id } })
export const queryOpsApplicationBindings = (id) => http.get('/api/v1/ops/application/bindings', { params: { id } })
export const saveOpsApplication = (data) => http.post('/api/v1/ops/application/save', data)
export const deleteOpsApplication = (id) => http.delete('/api/v1/ops/application/delete', { data: { id } })
export const queryOpsAppBuildTaskList = (params) => http.get('/api/v1/ops/application/build-task/list', { params })
export const opsAppBuildTaskInfo = (id) => http.get('/api/v1/ops/application/build-task/info', { params: { id } })
export const saveOpsAppBuildTask = (data) => http.post('/api/v1/ops/application/build-task/save', data)
export const updateOpsAppBuildTaskStatus = (data) => http.put('/api/v1/ops/application/build-task/status', data)
export const deleteOpsAppBuildTask = (id) => http.delete('/api/v1/ops/application/build-task/delete', { data: { id } })
export const runOpsAppBuildTask = (data) => http.post('/api/v1/ops/application/build-task/run', data)
export const runOpsAppRelease = (data) => http.post('/api/v1/ops/application/release/run', data)
export const retryOpsAppRelease = (id) => http.post('/api/v1/ops/application/release/retry', { id })
export const queryOpsAppReleaseList = (params) => http.get('/api/v1/ops/application/release/list', { params })
export const opsAppReleaseInfo = (id) => http.get('/api/v1/ops/application/release/info', { params: { id } })
export const queryOpsAppArtifactList = (params) => http.get('/api/v1/ops/application/artifact/list', { params })
export const queryOpsImageRegistryList = (params) => http.get('/api/v1/ops/application/image-registry/list', { params })
export const saveOpsImageRegistry = (data) => http.post('/api/v1/ops/application/image-registry/save', data)
export const deleteOpsImageRegistry = (id) => http.delete('/api/v1/ops/application/image-registry/delete', { data: { id } })
export const queryOpsAppPipelineTemplates = (params) => http.get('/api/v1/ops/application/pipeline/template/list', { params })
export const saveOpsAppPipelineTemplate = (data) => http.post('/api/v1/ops/application/pipeline/template/save', data)
export const normalizeOpsAppPipelineTemplateDefinition = (data) => http.post('/api/v1/ops/application/pipeline/template/normalize', data)
export const queryOpsAppPipelineList = (params) => http.get('/api/v1/ops/application/pipeline/list', { params })
export const opsAppPipelineInfo = (id) => http.get('/api/v1/ops/application/pipeline/info', { params: { id } })
export const saveOpsAppPipeline = (data) => http.post('/api/v1/ops/application/pipeline/save', data)
export const updateOpsAppPipelineStatus = (data) => http.put('/api/v1/ops/application/pipeline/status', data)
export const deleteOpsAppPipeline = (id) => http.delete('/api/v1/ops/application/pipeline/delete', { data: { id } })
export const copyOpsAppPipeline = (id) => http.post('/api/v1/ops/application/pipeline/copy', { id })
export const runOpsAppPipeline = (data) => http.post('/api/v1/ops/application/pipeline/run', data)
export const queryOpsAppPipelineRunList = (params) => http.get('/api/v1/ops/application/pipeline/run/list', { params })
export const opsAppPipelineRunInfo = (id) => http.get('/api/v1/ops/application/pipeline/run/info', { params: { id } })
export const approveOpsAppPipelineRun = (data) => http.post('/api/v1/ops/application/pipeline/run/approve', data)
export const rollbackOpsAppPipelineRun = (id) => http.post('/api/v1/ops/application/pipeline/run/rollback', { id })

export const queryOpsEnvironmentList = (params) => http.get('/api/v1/ops/environment/list', { params })
export const saveOpsEnvironment = (data) => http.post('/api/v1/ops/environment/save', data)
export const deleteOpsEnvironment = (id) => http.delete('/api/v1/ops/environment/delete', { data: { id } })

export const queryNotifyTemplateList = (params) => http.get('/api/v1/notify/template/list', { params })
export const queryNotifyTemplateOptions = (params) => http.get('/api/v1/notify/template/options', { params })
export const notifyTemplateInfo = (id) => http.get('/api/v1/notify/template/info', { params: { id } })
export const saveNotifyTemplate = (data) => http.post('/api/v1/notify/template/save', data)
export const deleteNotifyTemplate = (id) => http.delete('/api/v1/notify/template/delete', { data: { id } })

export const queryNotifyChannelList = (params) => http.get('/api/v1/notify/channel/list', { params })
export const queryNotifyChannelOptions = (params) => http.get('/api/v1/notify/channel/options', { params })
export const notifyChannelInfo = (id) => http.get('/api/v1/notify/channel/info', { params: { id } })
export const saveNotifyChannel = (data) => http.post('/api/v1/notify/channel/save', data)
export const deleteNotifyChannel = (id) => http.delete('/api/v1/notify/channel/delete', { data: { id } })

export const queryNotifyRuleList = (params) => http.get('/api/v1/notify/rule/list', { params })
export const queryNotifyRuleOptions = (params) => http.get('/api/v1/notify/rule/options', { params })
export const notifyRuleInfo = (id) => http.get('/api/v1/notify/rule/info', { params: { id } })
export const saveNotifyRule = (data) => http.post('/api/v1/notify/rule/save', data)
export const testNotifyRule = (id) => http.post('/api/v1/notify/rule/test', { id })
export const deleteNotifyRule = (id) => http.delete('/api/v1/notify/rule/delete', { data: { id } })

export const queryNotifySendLogList = (params) => http.get('/api/v1/notify/send-log/list', { params })
export const retryNotifySendLog = (id) => http.post('/api/v1/notify/send-log/retry', { id })
