<script setup>
import { onMounted, reactive, ref } from 'vue'
import { queryDNSAudit } from '../../api/domain'
const loading=ref(false),list=ref([]),total=ref(0)
const query=reactive({pageNum:1,pageSize:20})
function formatDateTime(value){const raw=String(value||'').trim();if(!raw)return '-';const match=raw.match(/^(\d{4}-\d{2}-\d{2})[T\s](\d{2}:\d{2}:\d{2})/);if(match)return `${match[1]} ${match[2]}`;const date=new Date(raw);if(Number.isNaN(date.getTime()))return raw;const pad=number=>String(number).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`}
async function load(){loading.value=true;try{const data=await queryDNSAudit(query);list.value=data.list||[];total.value=data.total||0}finally{loading.value=false}}
onMounted(load)
</script>
<template><section class="domain-page domain-panel page-card"><div class="domain-page-head"><div><div class="domain-eyebrow">DNS CHANGE AUDIT</div><h2>域名操作审计</h2><p>记录公网和内网 DNS 的操作人、来源、对象、旧值、新值与逐条执行结果。</p></div><el-button :loading="loading" @click="load">刷新</el-button></div><div class="domain-table-wrap"><el-table v-loading="loading" :data="list" border><el-table-column label="时间" width="180"><template #default="{row}">{{formatDateTime(row.createdAt)}}</template></el-table-column><el-table-column prop="username" label="操作用户" width="120"/><el-table-column prop="ipAddress" label="来源 IP" width="140"/><el-table-column prop="action" label="操作类型" min-width="170"/><el-table-column prop="provider" label="Provider" width="110"/><el-table-column prop="zone" label="Zone" min-width="150"/><el-table-column prop="domain" label="域名" min-width="210"><template #default="{row}"><span class="domain-mono">{{row.domain}}</span></template></el-table-column><el-table-column prop="recordType" label="类型" width="80"/><el-table-column label="变更" min-width="260"><template #default="{row}"><span class="domain-mono">{{row.oldValue||'—'}} → {{row.newValue||'—'}}</span></template></el-table-column><el-table-column label="结果" width="110"><template #default="{row}"><el-tooltip :content="row.error||'操作成功'"><el-tag :type="row.success?'success':'danger'">{{row.success?'成功':'失败'}}</el-tag></el-tooltip></template></el-table-column></el-table></div><div class="domain-pager"><el-pagination v-model:current-page="query.pageNum" v-model:page-size="query.pageSize" :page-sizes="[10,20,50,100]" layout="total, sizes, prev, pager, next" :total="total" @current-change="load" @size-change="query.pageNum=1;load()"/></div></section></template>
