<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { deleteInternalZone, getInternalDNSSettings, queryInternalZones, saveInternalZone } from '../../api/domain'
const router=useRouter(),loading=ref(false),zones=ref([]),dialogVisible=ref(false),saving=ref(false),runtime=ref({}),settings=ref({enabled:false}),settingsReady=ref(false),query=reactive({keyword:''}),form=reactive({id:0,name:'',description:'',status:1})
const dnsEnabled=computed(()=>Boolean(runtime.value.running))
function formatDateTime(value){const raw=String(value||'').trim();if(!raw)return '-';const match=raw.match(/^(\d{4}-\d{2}-\d{2})[T\s](\d{2}:\d{2}:\d{2})/);if(match)return `${match[1]} ${match[2]}`;const date=new Date(raw);if(Number.isNaN(date.getTime()))return raw;const pad=number=>String(number).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`}
async function loadZones(){loading.value=true;try{zones.value=(await queryInternalZones(query))||[]}finally{loading.value=false}}
async function loadSettings(){try{const data=await getInternalDNSSettings();settings.value=data.settings||{enabled:false};runtime.value=data.status||{}}finally{settingsReady.value=true}}
async function load(){await Promise.allSettled([loadZones(),loadSettings()])}
function create(){Object.assign(form,{id:0,name:'',description:'',status:1});dialogVisible.value=true}
function edit(row){Object.assign(form,row);dialogVisible.value=true}
async function save(){if(!form.name.trim()){ElMessage.warning('请输入 Zone 名称');return}saving.value=true;try{await saveInternalZone(form);ElMessage.success('Zone 已保存并实时刷新解析缓存');dialogVisible.value=false;await loadZones()}finally{saving.value=false}}
async function remove(row){await ElMessageBox.confirm(`删除 Zone“${row.name}”将同时删除全部解析记录，确认继续？`,'删除 Zone',{type:'warning'});await deleteInternalZone(row.id);ElMessage.success('Zone 已删除，解析立即失效');await loadZones()}
onMounted(load)
</script>
<template><section class="domain-page domain-panel page-card">
  <div class="domain-page-head"><div><div class="domain-eyebrow">PRIVATE DNS ZONES</div><h2>Zone 管理</h2><p>集中管理内网权威 Zone 与解析记录。Zone 内未命中的名称直接返回 NXDOMAIN，不向公网泄漏。</p></div><div><el-button @click="router.push('/domains/internal/settings')">DNS 设置</el-button><el-button v-permission="'domains:internal:zone:add'" type="primary" @click="create">新建 Zone</el-button></div></div>
  <div class="domain-stat-grid"><div class="domain-stat"><div class="domain-stat__label">DNS 状态</div><div style="margin-top:12px"><span class="dns-state" :class="{'is-running':runtime.running,'is-error':runtime.lastError}">{{!settingsReady?'检测中':runtime.running?'Running':runtime.lastError?'启动失败':'Stopped'}}</span></div></div><div class="domain-stat"><div class="domain-stat__label">监听地址</div><div class="domain-stat__value domain-mono" style="font-size:18px">{{runtime.listenAddress||'0.0.0.0:53'}}</div></div><div class="domain-stat"><div class="domain-stat__label">Zone 数量</div><div class="domain-stat__value">{{runtime.zoneCount||zones.length}}</div></div><div class="domain-stat"><div class="domain-stat__label">启用记录</div><div class="domain-stat__value">{{runtime.recordCount||0}}</div></div></div>
  <el-alert v-if="runtime.lastError" type="error" :closable="false" :title="runtime.lastError" show-icon/>
  <div v-if="settingsReady&&!dnsEnabled&&!runtime.lastError" class="dns-setup-notice" role="status"><div><strong>{{settings.enabled?'内网 DNS 服务当前未运行':'请先开启内网 DNS 服务'}}</strong><p>{{settings.enabled?'请检查监听端口和运行配置后重新启动服务。':'设置监听地址和上游 DNS 并启用服务后，才能对外提供内网域名解析。'}}</p></div><el-button type="primary" @click="router.push('/domains/internal/settings')">前往 DNS 设置</el-button></div>
  <div class="domain-toolbar" role="search"><div class="domain-toolbar__filters"><el-input v-model="query.keyword" clearable placeholder="搜索 Zone" style="width:260px" @keyup.enter="loadZones"/><el-button @click="loadZones">查询</el-button></div><div class="domain-toolbar__actions"><el-button :disabled="!dnsEnabled" @click="router.push('/domains/query-test')">解析测试</el-button></div></div>
  <div class="domain-table-wrap"><el-table v-loading="loading" :data="zones" border><el-table-column prop="name" label="Zone 名称" min-width="230"><template #default="{row}"><el-button link type="primary" class="domain-mono" @click="router.push(`/domains/internal/zones/${row.id}/records`)">{{row.name}}</el-button></template></el-table-column><el-table-column prop="description" label="描述" min-width="220"/><el-table-column prop="recordCount" label="记录数量" width="110"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status===1?'success':'info'">{{row.status===1?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="更新时间" width="180"><template #default="{row}">{{formatDateTime(row.updatedAt)}}</template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button link type="primary" @click="router.push(`/domains/internal/zones/${row.id}/records`)">解析记录</el-button><el-button v-permission="'domains:internal:zone:edit'" link @click="edit(row)">编辑</el-button><el-button v-permission="'domains:internal:zone:delete'" link type="danger" @click="remove(row)">删除</el-button></template></el-table-column><template #empty><div class="domain-empty"><strong>尚未创建内网 Zone</strong><p>{{dnsEnabled?'创建第一个 Zone，例如 ops.internal。':'可以先创建 Zone；启用 DNS 服务后，解析记录将立即生效。'}}</p><el-button v-permission="'domains:internal:zone:add'" type="primary" @click="create">新建 Zone</el-button></div></template></el-table></div>
  <el-dialog v-model="dialogVisible" :title="form.id?'编辑 Zone':'新建 Zone'" width="min(560px, calc(100vw - 32px))"><el-form label-width="92px"><el-form-item label="Zone 名称" required><el-input v-model="form.name" placeholder="ops.internal"/><div class="domain-form-tip">保存时自动转为小写并移除末尾的点。</div></el-form-item><el-form-item label="描述"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="状态"><el-switch v-model="form.status" :active-value="1" :inactive-value="2" active-text="启用" inactive-text="停用"/></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存 Zone</el-button></template></el-dialog>
</section></template>
