<script setup>
defineProps({ page: { type: Object, required: true } })
</script>

<template>
  <section class="embedded-workload-create">
    <header class="embedded-create-header"><el-button link type="primary" @click="page.workloadCreateVisible = false">← 返回工作负载</el-button><span class="workload-create-divider" /><strong>{{ page.cluster?.name || '当前集群' }}</strong><span>/</span><strong>工作负载</strong><span>/</span><span>创建 {{ page.workloadCreateForm.workloadType }}</span></header>
    <div class="pixiu-create-page">
      <el-form label-position="left" label-width="140px" class="pixiu-create-form">
        <section class="pixiu-form-section"><h3>基础配置</h3><div class="pixiu-form-body"><el-form-item label="工作负载类型"><el-radio-group v-model="page.workloadCreateForm.workloadType"><el-radio-button value="Deployment">部署 (Deployment)</el-radio-button><el-radio-button value="StatefulSet">有状态副本集</el-radio-button><el-radio-button value="DaemonSet">守护进程集</el-radio-button><el-radio-button value="Job">任务</el-radio-button><el-radio-button value="CronJob">定时任务</el-radio-button></el-radio-group></el-form-item><el-form-item label="名称" required><div><el-input v-model.trim="page.workloadCreateForm.name" placeholder="请输入工作负载名称" /><p class="pixiu-field-hint">最长 63 个字符，只能包含小写字母、数字及分隔符（-）。</p></div></el-form-item><el-form-item label="命名空间" required><el-select v-model="page.workloadCreateForm.namespace"><el-option v-for="item in page.namespaceOptions.filter((option) => option.value !== '__all__')" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item v-if="!['DaemonSet', 'Job', 'CronJob'].includes(page.workloadCreateForm.workloadType)" label="实例数量"><el-input-number v-model="page.workloadCreateForm.replicas" :min="1" :max="100" /></el-form-item></div></section>
        <section class="pixiu-form-section"><h3>容器配置</h3><div class="pixiu-form-body"><div class="pixiu-container-card"><div class="pixiu-container-title">container-1</div><el-form-item label="容器名称" required><el-input v-model.trim="page.workloadCreateForm.containerName" placeholder="请输入容器名称" /></el-form-item><el-form-item label="镜像" required><el-input v-model.trim="page.workloadCreateForm.image" placeholder="请输入完整的镜像地址" /></el-form-item><el-form-item label="拉取策略"><el-radio-group v-model="page.workloadCreateForm.imagePullPolicy"><el-radio-button value="Always">Always</el-radio-button><el-radio-button value="IfNotPresent">IfNotPresent</el-radio-button><el-radio-button value="Never">Never</el-radio-button></el-radio-group></el-form-item><el-form-item label="容器端口"><el-input-number v-model="page.workloadCreateForm.containerPort" :min="1" :max="65535" /></el-form-item><el-form-item label="CPU / 内存限制"><div class="pixiu-resource-row"><el-input v-model.trim="page.workloadCreateForm.requestCPU" placeholder="CPU request，例如 100m" /><el-input v-model.trim="page.workloadCreateForm.limitCPU" placeholder="CPU limit，例如 500m" /><el-input v-model.trim="page.workloadCreateForm.requestMemory" placeholder="内存 request，例如 128Mi" /><el-input v-model.trim="page.workloadCreateForm.limitMemory" placeholder="内存 limit，例如 512Mi" /></div></el-form-item></div></div></section>
        <section class="pixiu-form-section"><h3>访问设置（Service）</h3><div class="pixiu-form-body"><el-form-item label="Service"><el-checkbox v-model="page.workloadCreateForm.createService">启用，同时创建 Service</el-checkbox></el-form-item><template v-if="page.workloadCreateForm.createService"><el-form-item label="服务名称"><el-input v-model.trim="page.workloadCreateForm.serviceName" :placeholder="page.workloadCreateForm.name || '不填默认与工作负载名称相同'" /></el-form-item><el-form-item label="服务访问方式"><el-radio-group v-model="page.workloadCreateForm.serviceType"><el-radio value="ClusterIP">仅在集群内访问</el-radio><el-radio value="NodePort">主机端口访问</el-radio><el-radio value="LoadBalancer">LoadBalancer</el-radio></el-radio-group></el-form-item><el-form-item label="端口映射"><div class="pixiu-port-row"><el-input-number v-model="page.workloadCreateForm.servicePort" :min="1" :max="65535" /><span>Service 端口 →</span><el-input v-model.trim="page.workloadCreateForm.targetPort" :placeholder="String(page.workloadCreateForm.containerPort)" /></div></el-form-item></template></div></section>
        <section class="pixiu-form-section"><h3>应用路由（Ingress）</h3><div class="pixiu-form-body"><el-form-item label="Ingress"><el-checkbox v-model="page.workloadCreateForm.createIngress" :disabled="!page.workloadCreateForm.createService">启用，同时创建 Ingress</el-checkbox></el-form-item><template v-if="page.workloadCreateForm.createIngress"><el-form-item label="访问域名" required><el-input v-model.trim="page.workloadCreateForm.ingressHost" placeholder="例如 api.example.com" /></el-form-item><el-form-item label="路径"><div class="pixiu-port-row"><el-input v-model.trim="page.workloadCreateForm.ingressPath" /><el-select v-model="page.workloadCreateForm.ingressPathType"><el-option label="Prefix" value="Prefix" /><el-option label="Exact" value="Exact" /></el-select></div></el-form-item><el-form-item label="Ingress Class"><el-input v-model.trim="page.workloadCreateForm.ingressClassName" placeholder="例如 nginx（可选）" /></el-form-item></template></div></section>
      </el-form>
      <footer class="pixiu-create-footer"><el-button @click="page.workloadCreateVisible = false">取消</el-button><el-button type="primary" :loading="page.workloadCreateSaving" @click="page.submitWorkloadCreate">创建 {{ page.workloadCreateForm.workloadType }}</el-button></footer>
    </div>
  </section>
</template>
